# Generated by Django 6.0.7 on 2026-08-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimony',
            name='project',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
