# Generated by Django 6.0.7 on 2026-08-06 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0002_testimony_contact_testimony_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimony',
            old_name='author',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='testimony',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='testimony',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='testimony',
            name='project',
        ),
    ]
